<a href="https://colab.research.google.com/github/t1nh233/Pytorch-AI-Research-Roadmap/blob/main/Day_01_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# --- STARTUP BLOCK ---
import os
import torch
import numpy as np

# 1. Kết nối Google Drive (Để lấy dữ liệu)
from google.colab import drive
drive.mount('/content/drive')

# 2. Tạo đường dẫn tắt (Để code cho gọn)
# Lưu ý: Sửa lại đúng tên thư mục bạn tạo ở Bước 2 phần trên
DATA_PATH = '/content/drive/MyDrive/Pytorch_AI_Research_Bootcamp/datasets'
MODEL_PATH = '/content/drive/MyDrive/Pytorch_AI_Research_Bootcamp/checkpoints'

# 3. Kiểm tra GPU
if torch.cuda.is_available():
    print(f"✅ Đã bật GPU: {torch.cuda.get_device_name(0)}")
else:
    print("⚠️ Cảnh báo: Bạn đang chạy bằng CPU. Hãy vào Runtime -> Change runtime type -> T4 GPU")

# 4. Tạo thư mục nếu chưa có (Tránh lỗi)
os.makedirs(DATA_PATH, exist_ok=True)
os.makedirs(MODEL_PATH, exist_ok=True)

print("🚀 Môi trường đã sẵn sàng!")

Mounted at /content/drive
✅ Đã bật GPU: Tesla T4
🚀 Môi trường đã sẵn sàng!


- Tạo tensor **0 chiều** (scalar): `x = torch.tensor(5.0)`.
- Tạo tensor **ngẫu nhiên** shape `(3, 4)` dùng `torch.randn`.
- Tạo tensor **toàn số 0** và **toàn số 1**.

In [7]:
#Tao tensor 0 chieu (scalar):

x = torch.tensor(14.0)
y = torch.tensor(23.0)
z = torch.tensor(8.0)

print("Tensor x:\n", x)
print("Tensor y:\n", y)
print("Tensor z:\n", z)

Tensor x:
 tensor(14.)
Tensor y:
 tensor(23.)
Tensor z:
 tensor(8.)


In [9]:
#Tao tensor ngau nhieu voi shape

x_rand = torch.randn(3, 4)
y_rand = torch.randn(14, 8)
z_rand = torch.randn(10, 9, 3)

print("Tensor x_rand:\n", x_rand)
print("Tensor y_rand:\n", y_rand)
print("Tensor z_rand:\n", z_rand)

Tensor x_rand:
 tensor([[-0.5932, -2.1588,  2.0830, -2.7309],
        [-1.4837, -1.2145,  0.0926,  1.3870],
        [-0.7146, -0.0622,  0.0796, -2.3740]])
Tensor y_rand:
 tensor([[ 2.3325,  1.6621, -1.2303, -0.3302, -0.8475,  1.2304,  1.0407,  1.2043],
        [ 1.6535, -1.2542, -0.6823,  1.3294, -0.3215, -0.6320,  0.6264, -0.4458],
        [-0.5849,  0.7431, -0.9642, -0.2591,  1.7371, -0.1053,  1.1080, -0.5658],
        [-0.8203,  1.0192, -0.8290, -0.4003,  1.1367,  1.1904, -0.1700,  0.5910],
        [ 0.9151, -1.4927, -0.7624, -0.9186,  0.1849, -0.6045,  1.2103, -0.9304],
        [-0.2956, -0.8421,  0.3718,  0.0376, -0.7891, -0.9196,  1.3127, -0.8013],
        [-0.0939,  0.8849, -1.2598, -0.2118, -0.3858, -0.0324,  2.3494, -0.9419],
        [ 0.0055,  0.2409, -2.2869,  0.8585,  0.0707,  1.0467,  0.8161, -0.8058],
        [-0.7481,  2.2285, -0.6001,  0.1803,  0.1286,  0.6205,  0.7555,  1.0076],
        [ 0.8007,  0.0715, -0.6158,  0.8497, -0.3032,  0.3908,  0.0439, -0.7139],
        [

In [10]:
#Tao tensor toan so 0 va toan so 1

all_ones = torch.ones(10, 5)
all_zeros = torch.zeros(4, 11)

print("Tensor all_ones:\n", all_ones)
print("Tensor all_zeros:\n", all_zeros)

Tensor all_ones:
 tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
Tensor all_zeros:
 tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])


- Kiểm tra `x.dtype`. Thử ép kiểu từ `float32` sang `int64` bằng `.long()`.
- Đẩy tensor sang GPU: `x = x.to('cuda')` (Nếu dùng Colab). Kiểm tra lại `.device`.

In [16]:
#Kiem tra .dtype va ep kieu tu float32 sang int64

print("Dtype cua x la: ", x.dtype)

y_int64 = y.long()
print("Dtype ban dau cua y la: ", y.dtype)
print("Dtype sau khi ep kieu cua y la: ", y_int64.dtype)

x_float64 = x.to(torch.float64)
print("Dtype cua x sau khi ep: ", x_float64.dtype)

Dtype cua x la:  torch.float32
Dtype ban dau cua y la:  torch.float32
Dtype sau khi ep kieu cua y la:  torch.int64
Dtype cua x sau khi ep:  torch.float64


In [18]:
#Day tensor sang GPU

x_float64 = x_float64.to('cuda')
print("x_float64 gio dang o ", x_float64.device)

x_float64 gio dang o  cuda:0


- Tạo ma trận `A` shape `(3, 3)` và vector `b` shape `(1, 3)`.
- Thực hiện `A + b`. Giải thích tại sao cộng được dù khác kích thước?
- Thực hiện nhân ma trận: `A @ A` (hoặc `torch.matmul`).

In [19]:
#Tao ma tran A va vector b

A = torch.randn(3, 3)
b = torch.randn(1, 3)

print("Ma tran A:\n", A)
print("Vector b:\n", b)

Ma tran A:
 tensor([[ 0.0385,  0.2516, -0.0934],
        [-1.4981, -1.6220,  1.2140],
        [ 0.5246, -1.4078, -1.2921]])
Vector b:
 tensor([[-2.3191, -0.5391,  0.3690]])


In [21]:
#Thuc hien A + b

sum_Ab = A + b
print("Ket qua cua phep tinh: A + b\n", sum_Ab)

#Giai thich vi broadcasting duoc tren shape cua A va cua b

Ket qua cua phep tinh: A + b
 tensor([[-2.2807, -0.2875,  0.2756],
        [-3.8173, -2.1611,  1.5830],
        [-1.7946, -1.9470, -0.9231]])


In [25]:
#Phep nhan ma tran A * (A + b)

mulA_sumAb = A @ (A + b)
print("Ket qua cua phep tinh: A * (A + b)\n", mulA_sumAb)

#hoac co the su dung matmul nhu sau

mulA_sumAb_ = torch.matmul(A, A + b)
print("Ket qua cua phep tinh (su dung matmul): A * (A + b)\n", mulA_sumAb_)

#kiem tra xem co giong nhau khong

print("Giong nhau khong: ", torch.allclose(mulA_sumAb, mulA_sumAb_))

Ket qua cua phep tinh: A * (A + b)
 tensor([[-0.8806, -0.3730,  0.4951],
        [ 7.4295,  1.5723, -4.1012],
        [ 6.4965,  5.4073, -0.8912]])
Ket qua cua phep tinh (su dung matmul): A * (A + b)
 tensor([[-0.8806, -0.3730,  0.4951],
        [ 7.4295,  1.5723, -4.1012],
        [ 6.4965,  5.4073, -0.8912]])
Giong nhau khong:  True


- Tạo tensor `x` shape `(2, 3, 4)`.
- Dùng `.view()` hoặc `.reshape()` để đổi thành `(2, 12)`.
- Dùng `.permute(0, 2, 1)` để đổi thành `(2, 4, 3)`. In `.shape` ra để kiểm tra.

In [28]:
#Tao tensor thu voi shape (2, 3, 4)

tensor_thu = torch.randn(2, 3, 4)
print("Tensor vua duoc tao voi shape (2, 3, 4): \n", tensor_thu)

#Dung view va reshape de doi shape thanh (2, 12)

tensor_thu_view = tensor_thu.view(2, 12)
tensor_thu_reshape = tensor_thu.reshape(2, 12)

print("Tensor sau khi dung view: \n", tensor_thu_view)
print("Tensor sau khi dung reshape: \n", tensor_thu_reshape)

#Dung permute(0, 2, 1) de doi thanh (2, 4, 3)

tensor_thu_permute = tensor_thu.permute(0, 2, 1)
print("Tensor ban dau sau khi permute(0, 2, 1): \n", tensor_thu_permute)

Tensor vua duoc tao voi shape (2, 3, 4): 
 tensor([[[-2.8530, -0.8970, -0.6790,  0.5155],
         [-1.5395,  1.3213, -2.2652,  0.3315],
         [ 0.7827, -0.6087,  0.6680, -0.8182]],

        [[-0.8264, -0.9609, -2.8192, -1.0402],
         [ 0.6593, -1.7187, -1.2421, -1.6424],
         [ 0.0942,  0.2812,  0.5812,  1.6015]]])
Tensor sau khi dung view: 
 tensor([[-2.8530, -0.8970, -0.6790,  0.5155, -1.5395,  1.3213, -2.2652,  0.3315,
          0.7827, -0.6087,  0.6680, -0.8182],
        [-0.8264, -0.9609, -2.8192, -1.0402,  0.6593, -1.7187, -1.2421, -1.6424,
          0.0942,  0.2812,  0.5812,  1.6015]])
Tensor sau khi dung reshape: 
 tensor([[-2.8530, -0.8970, -0.6790,  0.5155, -1.5395,  1.3213, -2.2652,  0.3315,
          0.7827, -0.6087,  0.6680, -0.8182],
        [-0.8264, -0.9609, -2.8192, -1.0402,  0.6593, -1.7187, -1.2421, -1.6424,
          0.0942,  0.2812,  0.5812,  1.6015]])
Tensor ban dau sau khi permute(0, 2, 1): 
 tensor([[[-2.8530, -1.5395,  0.7827],
         [-0.8970,  1