<a href="https://colab.research.google.com/github/t1nh233/Pytorch-AI-Research-Roadmap/blob/main/Day_02_Autograd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [23]:
# --- STARTUP BLOCK ---
import os
import torch
import numpy as np

# 1. Kết nối Google Drive (Để lấy dữ liệu)
from google.colab import drive
drive.mount('/content/drive')

# 2. Tạo đường dẫn tắt (Để code cho gọn)
# Lưu ý: Sửa lại đúng tên thư mục bạn tạo ở Bước 2 phần trên
DATA_PATH = '/content/drive/MyDrive/Pytorch_AI_Research_Bootcamp/datasets'
MODEL_PATH = '/content/drive/MyDrive/Pytorch_AI_Research_Bootcamp/checkpoints'

# 3. Kiểm tra GPU
if torch.cuda.is_available():
    print(f"✅ Đã bật GPU: {torch.cuda.get_device_name(0)}")
else:
    print("⚠️ Cảnh báo: Bạn đang chạy bằng CPU. Hãy vào Runtime -> Change runtime type -> T4 GPU")

# 4. Tạo thư mục nếu chưa có (Tránh lỗi)
os.makedirs(DATA_PATH, exist_ok=True)
os.makedirs(MODEL_PATH, exist_ok=True)

print("🚀 Môi trường đã sẵn sàng!")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
✅ Đã bật GPU: Tesla T4
🚀 Môi trường đã sẵn sàng!


In [24]:
x = torch.tensor([2.0, 3.0], requires_grad=True)
y = x**2 + 3*x + 1
z = y.sum()
print(y)
print(z)

tensor([11., 19.], grad_fn=<AddBackward0>)
tensor(30., grad_fn=<SumBackward0>)


In [25]:
#Goi backward

z.backward(retain_graph=True)
print(x.grad)
z.backward()
print(x.grad)

tensor([7., 9.])
tensor([14., 18.])


In [28]:
#Vay neu toi boc tat ca trong no_grad() thi sao

with torch.no_grad():
  k = x**2 + 3*x + 1

print(y.grad_fn)
print(k.requires_grad)
print(k.grad_fn)
print(y.grad_fn.next_functions)

False
None
((<AddBackward0 object at 0x7afcd0c184f0>, 0), (None, 0))
