<a href="https://colab.research.google.com/github/t1nh233/Pytorch-AI-Research-Roadmap/blob/main/Day_01_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# --- STARTUP BLOCK ---
import os
import torch
import numpy as np

# 1. Kết nối Google Drive (Để lấy dữ liệu)
from google.colab import drive
drive.mount('/content/drive')

# 2. Tạo đường dẫn tắt (Để code cho gọn)
# Lưu ý: Sửa lại đúng tên thư mục bạn tạo ở Bước 2 phần trên
DATA_PATH = '/content/drive/MyDrive/Pytorch_AI_Research_Bootcamp/datasets'
MODEL_PATH = '/content/drive/MyDrive/Pytorch_AI_Research_Bootcamp/checkpoints'

# 3. Kiểm tra GPU
if torch.cuda.is_available():
    print(f"✅ Đã bật GPU: {torch.cuda.get_device_name(0)}")
else:
    print("⚠️ Cảnh báo: Bạn đang chạy bằng CPU. Hãy vào Runtime -> Change runtime type -> T4 GPU")

# 4. Tạo thư mục nếu chưa có (Tránh lỗi)
os.makedirs(DATA_PATH, exist_ok=True)
os.makedirs(MODEL_PATH, exist_ok=True)

print("🚀 Môi trường đã sẵn sàng!")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
✅ Đã bật GPU: Tesla T4
🚀 Môi trường đã sẵn sàng!


- Tạo tensor **0 chiều** (scalar): `x = torch.tensor(5.0)`.
- Tạo tensor **ngẫu nhiên** shape `(3, 4)` dùng `torch.randn`.
- Tạo tensor **toàn số 0** và **toàn số 1**.

In [3]:
#Tao tensor 0 chieu (scalar):

x = torch.tensor(14.0)
y = torch.tensor(23.0)
z = torch.tensor(8.0)

print("Tensor x:\n", x)
print("Tensor y:\n", y)
print("Tensor z:\n", z)

Tensor x:
 tensor(14.)
Tensor y:
 tensor(23.)
Tensor z:
 tensor(8.)


In [4]:
#Tao tensor ngau nhieu voi shape

x_rand = torch.randn(3, 4)
y_rand = torch.randn(14, 8)
z_rand = torch.randn(10, 9, 3)

print("Tensor x_rand:\n", x_rand)
print("Tensor y_rand:\n", y_rand)
print("Tensor z_rand:\n", z_rand)

Tensor x_rand:
 tensor([[-0.9052, -0.0692, -1.2920, -0.0168],
        [ 0.1359,  1.4648,  0.9534, -0.1541],
        [-0.7046,  1.3131, -0.4809, -1.1916]])
Tensor y_rand:
 tensor([[-1.0486, -2.3898,  1.2042,  1.0185, -0.8209,  0.3156,  0.1979,  1.1426],
        [ 0.7328, -0.4855, -0.2312,  0.1526,  1.2300, -0.3344,  0.5314, -0.1338],
        [ 1.4498, -0.7368,  0.1207, -0.9121, -0.6570, -0.4273,  0.4627, -1.2656],
        [ 1.4988,  1.5056,  0.1399,  1.3716, -0.6010, -0.8883,  1.5361,  0.2925],
        [ 0.2978,  1.1204, -2.0165, -0.5317, -0.8719,  0.5063, -0.9164, -0.9646],
        [-0.5533, -0.2385, -0.5604, -0.7070,  0.2859,  0.7295,  0.3328, -0.3750],
        [-0.8317, -0.5295, -0.1496,  0.2988,  0.5547, -0.6818, -0.0740,  1.2048],
        [-1.1175,  0.3616, -1.1645, -0.4717,  0.8164, -0.0944, -0.5640, -0.3567],
        [ 0.8026,  1.7843,  0.6399, -0.3916, -0.3638, -0.2896,  0.4710, -1.3318],
        [ 0.7854, -0.6858, -0.4985, -0.8000,  0.1401,  0.8613,  0.5746,  0.7770],
        [

In [5]:
#Tao tensor toan so 0 va toan so 1

all_ones = torch.ones(10, 5)
all_zeros = torch.zeros(4, 11)

print("Tensor all_ones:\n", all_ones)
print("Tensor all_zeros:\n", all_zeros)

Tensor all_ones:
 tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
Tensor all_zeros:
 tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])


- Kiểm tra `x.dtype`. Thử ép kiểu từ `float32` sang `int64` bằng `.long()`.
- Đẩy tensor sang GPU: `x = x.to('cuda')` (Nếu dùng Colab). Kiểm tra lại `.device`.

In [6]:
#Kiem tra .dtype va ep kieu tu float32 sang int64

print("Dtype cua x la: ", x.dtype)

y_int64 = y.long()
print("Dtype ban dau cua y la: ", y.dtype)
print("Dtype sau khi ep kieu cua y la: ", y_int64.dtype)

x_float64 = x.to(torch.float64)
print("Dtype cua x sau khi ep: ", x_float64.dtype)

Dtype cua x la:  torch.float32
Dtype ban dau cua y la:  torch.float32
Dtype sau khi ep kieu cua y la:  torch.int64
Dtype cua x sau khi ep:  torch.float64


In [7]:
#Day tensor sang GPU

x_float64 = x_float64.to('cuda')
print("x_float64 gio dang o ", x_float64.device)

x_float64 gio dang o  cuda:0


- Tạo ma trận `A` shape `(3, 3)` và vector `b` shape `(1, 3)`.
- Thực hiện `A + b`. Giải thích tại sao cộng được dù khác kích thước?
- Thực hiện nhân ma trận: `A @ A` (hoặc `torch.matmul`).

In [8]:
#Tao ma tran A va vector b

A = torch.randn(3, 3)
b = torch.randn(1, 3)

print("Ma tran A:\n", A)
print("Vector b:\n", b)

Ma tran A:
 tensor([[ 1.4165, -1.2856, -0.2015],
        [-0.5986,  0.4113, -0.8275],
        [-0.6942,  0.0728, -0.4096]])
Vector b:
 tensor([[ 1.4139, -0.5796,  0.6503]])


In [9]:
#Thuc hien A + b

sum_Ab = A + b
print("Ket qua cua phep tinh: A + b\n", sum_Ab)

#Giai thich vi broadcasting duoc tren shape cua A va cua b

Ket qua cua phep tinh: A + b
 tensor([[ 2.8304, -1.8652,  0.4487],
        [ 0.8153, -0.1683, -0.1773],
        [ 0.7197, -0.5068,  0.2407]])


In [10]:
#Phep nhan ma tran A * (A + b)

mulA_sumAb = A @ (A + b)
print("Ket qua cua phep tinh: A * (A + b)\n", mulA_sumAb)

#hoac co the su dung matmul nhu sau

mulA_sumAb_ = torch.matmul(A, A + b)
print("Ket qua cua phep tinh (su dung matmul): A * (A + b)\n", mulA_sumAb_)

#kiem tra xem co giong nhau khong

print("Giong nhau khong: ", torch.allclose(mulA_sumAb, mulA_sumAb_))

Ket qua cua phep tinh: A * (A + b)
 tensor([[ 2.8160, -2.3234,  0.8150],
        [-1.9546,  1.4667, -0.5407],
        [-2.2002,  1.4901, -0.4230]])
Ket qua cua phep tinh (su dung matmul): A * (A + b)
 tensor([[ 2.8160, -2.3234,  0.8150],
        [-1.9546,  1.4667, -0.5407],
        [-2.2002,  1.4901, -0.4230]])
Giong nhau khong:  True


- Tạo tensor `x` shape `(2, 3, 4)`.
- Dùng `.view()` hoặc `.reshape()` để đổi thành `(2, 12)`.
- Dùng `.permute(0, 2, 1)` để đổi thành `(2, 4, 3)`. In `.shape` ra để kiểm tra.

In [11]:
#Tao tensor thu voi shape (2, 3, 4)

tensor_thu = torch.randn(2, 3, 4)
print("Tensor vua duoc tao voi shape (2, 3, 4): \n", tensor_thu)

#Dung view va reshape de doi shape thanh (2, 12)

tensor_thu_view = tensor_thu.view(2, 12)
tensor_thu_reshape = tensor_thu.reshape(2, 12)

print("Tensor sau khi dung view: \n", tensor_thu_view)
print("Tensor sau khi dung reshape: \n", tensor_thu_reshape)

#Dung permute(0, 2, 1) de doi thanh (2, 4, 3)

tensor_thu_permute = tensor_thu.permute(0, 2, 1)
print("Tensor ban dau sau khi permute(0, 2, 1): \n", tensor_thu_permute)

Tensor vua duoc tao voi shape (2, 3, 4): 
 tensor([[[ 0.6898, -1.4033,  0.4636,  0.2105],
         [ 0.1975,  0.7635,  0.3953,  0.2275],
         [ 0.6479,  0.3117,  1.3205, -0.6968]],

        [[-0.1559,  0.5201,  0.6380,  0.7952],
         [-0.8531,  1.1610, -1.5083,  0.6843],
         [ 1.7667,  0.9140,  0.9598,  0.4226]]])
Tensor sau khi dung view: 
 tensor([[ 0.6898, -1.4033,  0.4636,  0.2105,  0.1975,  0.7635,  0.3953,  0.2275,
          0.6479,  0.3117,  1.3205, -0.6968],
        [-0.1559,  0.5201,  0.6380,  0.7952, -0.8531,  1.1610, -1.5083,  0.6843,
          1.7667,  0.9140,  0.9598,  0.4226]])
Tensor sau khi dung reshape: 
 tensor([[ 0.6898, -1.4033,  0.4636,  0.2105,  0.1975,  0.7635,  0.3953,  0.2275,
          0.6479,  0.3117,  1.3205, -0.6968],
        [-0.1559,  0.5201,  0.6380,  0.7952, -0.8531,  1.1610, -1.5083,  0.6843,
          1.7667,  0.9140,  0.9598,  0.4226]])
Tensor ban dau sau khi permute(0, 2, 1): 
 tensor([[[ 0.6898,  0.1975,  0.6479],
         [-1.4033,  0

Bài tập ôn tập cuối buổi

In [18]:
##Khoi tao du lieu tho

batch_images = torch.randn((10, 3, 64, 64))

print(f"Shape gốc: {batch_images.shape}")
print(f"Địa chỉ gốc: {batch_images.data_ptr()}")

Shape gốc: torch.Size([10, 3, 64, 64])
Địa chỉ gốc: 1131163904


In [21]:
##Trich xuat & luu tru

flat_images = batch_images.view(10, -1)
print(f"Shape sau khi flatten: {flat_images.shape}")
print(f"Địa chỉ sau khi flatten: {flat_images.data_ptr()}")


##Khi thay doi gia tri dau tien cua flat_images xem batch_images co thay doi khong

print(f"Gia tri batch_images goc (ban dau): {batch_images[0, 0, 0, 0]}")
flat_images[0, 0] = 999.0
print(f"Gia tri batch_images sau khi thay doi: {batch_images[0, 0, 0, 0]}")

Shape sau khi flatten: torch.Size([10, 12288])
Địa chỉ sau khi flatten: 1131163904
Gia tri batch_images goc (ban dau): 999.0
Gia tri batch_images sau khi thay doi: 999.0


In [28]:
##Xoay truc va tuong tac voi stride

permuted_images = torch.permute(batch_images, (0, 2, 3, 1))
print(f"Shape sau khi permute: {permuted_images.shape}")
print(f"Địa chỉ sau khi permute: {permuted_images.data_ptr()}")

print(f"Stride cua batch_images: {batch_images.stride()}")
print(f"Stride cua permuted_images: {permuted_images.stride()}")

##Kiem tra xem permuted_images co contiguous

print(f"permuted_images co contiguous: {permuted_images.is_contiguous()}")

##Khong lien tiep (contiguous) thi cach giai quyet

contiguous_images = permuted_images.contiguous()

##Kiem tra lai sau khi giai quyet

print(f"contiguous_images co contiguous: {contiguous_images.is_contiguous()}")
print(f"Stride cua contiguous_images: {contiguous_images.stride()}")

Shape sau khi permute: torch.Size([10, 64, 64, 3])
Địa chỉ sau khi permute: 1131163904
Stride cua batch_images: (12288, 4096, 64, 1)
Stride cua permuted_images: (12288, 64, 1, 4096)
permuted_images co contiguous: False
contiguous_images co contiguous: True
Stride cua contiguous_images: (12288, 192, 3, 1)


In [30]:
##Su ket noi giua numpy va GPU

np_images = batch_images.numpy()

print(f"Mean (NumPy): {np.mean(np_images):.4f}")

# Đưa lên GPU (Nếu có)
if torch.cuda.is_available():
    print("Đang đẩy lên GPU...")
    batch_gpu = batch_images.to('cuda')

    # Thử convert ngược về NumPy (Sẽ lỗi)
    try:
        tmp = batch_gpu.numpy()
    except TypeError as e:
        print(f"LỖI BẮT ĐƯỢC: {e}")
        print("-> Giải pháp: Phải dùng .cpu().numpy()")
        tmp = batch_gpu.cpu().numpy()
        print("Đã fix thành công!")
else:
    print("Máy không có GPU để test phần này.")

Mean (NumPy): 0.0095
Đang đẩy lên GPU...
LỖI BẮT ĐƯỢC: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.
-> Giải pháp: Phải dùng .cpu().numpy()
Đã fix thành công!


In [32]:
##Broadcasting tensor

brightness = torch.tensor([0.1, 0.2, 0.3]).view(3, 1, 1)
print(f"Brightness shape: {brightness.shape}")

result = brightness + batch_images
print(f"Result shape: {result.shape}")

Brightness shape: torch.Size([3, 1, 1])
Result shape: torch.Size([10, 3, 64, 64])
